source 'https://rubygems.org'

# gem 'kitchen-dokken', '~> 2.6'
gem 'kitchen-dokken'

gem 'guard-kitchen',  github: 'trickyearlobe/guard-kitchen', branch: 'support_guard_2'
gem 'guard-foodcritic'
gem 'guard-rspec'
gem 'guard'
gem 'foodcritic'
gem 'pry-coolline'
# gem 'chefspec', '~> 7.1.0'
gem 'berkshelf'
# gem 'inspec'
gem 'kitchen-inspec'